name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -e backend[test]
      - name: Run backend tests
        run: pytest
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install frontend deps
        working-directory: frontend
        run: npm install
      - name: Run frontend tests
        working-directory: frontend
        run: npm run test
